# ================================================================
#   Configuração do Log4j2 no Spring Boot
# ================================================================
# N�vel padrão do root logger
logging.level.root=INFO
# Logger específico para o seu pacote
logging.level.br.com.ramiralvesmelo.util=ERROR
# Padrão de log no console
logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
# Caminho e nome do arquivo de log
logging.file.name=/tmp/logs/util.log
# Padrão de log no arquivo
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n